FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app_lib ./app_lib
COPY streamlit_app ./streamlit_app
COPY data/raw ./data/raw

ENV PYTHONPATH=/app
ENV MODEL_API_URL=http://api:8080

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
